### ISSUE TITLE
Not all specified weapons in items.cfg spawn

### ISSUE THREAD

**Issue by kingofings** [rogeraabbccdd/CSGO-Super-Smash-Bros-CSGOWeapons#1]
Not all weapons in the items.cfg will even spawn. From what i have observed only the top 13 are ever spawned and the ones below them never. 

I'll attach my items config below (renamed to txt github doesn't support .cfg)

[items.txt](https://github.com/rogeraabbccdd/CSGO-Super-Smash-Bros-CSGOWeapons/files/5708489/items.txt)

All items below "item_blackhole" never spawn.

System Info

Ubuntu 20.04.1 LTS
Sourcemod 1.10.0.6501
Metamod 1.11.0-dev+1143

**Comment by rogeraabbccdd** [comment]
This is not caused by this plugin.
Please create your issue at [CSGO-Super-Smash-Bros](https://github.com/rogeraabbccdd/CSGO-Super-Smash-Bros)
